### Get All Products

GET {{url}}/product/all
Accept: application/json

### Get Product with ID

GET {{url}}/product/1
Accept: application/json

### Create new Product

POST {{url}}/product/
Content-Type: application/json

{
    "productName" : "Test Prodcut Iphone",
    "userId" : 1
}

### Update Product on ID

PUT {{url}}/product/1
Content-Type: application/json

{
    "productName" : "Updated Test Iphone",
    "userId" : "1",
    "warrantyId" : "1"
}

### Delete Product on ID

DELETE {{url}}/product/1