@baseUrl = http://localhost:7070/productRegistration

### Get All ProductRegistrations

GET {{baseUrl}}/all

### Get ProductRegistration with ID

GET {{baseUrl}}/1

### Create new ProductRegistration

POST {{baseUrl}}/
Content-Type: application/json

{
    "userId" : 1,
    "productId" : 2,
    "purchasedAt" : "2026-04-05",
    "registeredAt" : "2026-04-05"
}

### Update ProductRegistration on ID

PUT {{baseUrl}}/4
Content-Type: application/json

{
    "userId" : 2,
    "productId" : 2,
    "purchasedAt" : "2026-06-06",
    "registeredAt" : "2026-06-06"
}

### Delete ProductRegistration on ID

DELETE {{baseUrl}}/1