### Get All ProductRegistrations

GET {{url}}/product-registration/all
Accept: application/json

### Get ProductRegistration with ID

GET {{url}}/product-registration/1
Accept: application/json

### Create new ProductRegistration

POST {{url}}/product-registration/
Content-Type: application/json

{
    "userId" : 1,
    "productId" : 2,
    "purchasedAt" : "2026-04-05",
    "registeredAt" : "2026-04-05"
}

### Update ProductRegistration on ID

PUT {{url}}/product-registration/4
Content-Type: application/json

{
    "userId" : 2,
    "productId" : 2,
    "purchasedAt" : "2026-06-06",
    "registeredAt" : "2026-06-06"
}

### Delete ProductRegistration on ID

DELETE {{url}}/product-registration/1