### Get All Products
GET {{url}}/product/all
Accept: application/json
Authorization: Bearer {{token}}

### Get Product with ID
GET {{url}}/product/1
Accept: application/json
Authorization: Bearer {{token}}

### Create new Product
POST {{url}}/product/
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "productName" : "Test Prodcut Iphone",
    "userId" : 1
}

### Update Product on ID
PUT {{url}}/product/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "productName" : "Updated Test Iphone",
    "userId" : "1",
    "warrantyId" : "1"
}

### Delete Product on ID
DELETE {{url}}/product/1
Authorization: Bearer {{token}}