### Get All Receipts

GET {{url}}/receipt/all
Accept: application/json

### Get Receipt with ID

GET {{url}}/receipt/1
Accept: application/json

### Create new Receipt

POST {{url}}/receipt/
Content-Type: application/json

{
  "productRegistrationId" : 1,
  "purchasedAt" : "2026-04-05",
  "description" : "A BRAND NEW IMAC",
  "price" : 1500.30
}

### Update Receipt on ID

PUT {{url}}/receipt/1
Content-Type: application/json

{
  "productRegistrationId" : 1,
  "purchasedAt" : "2026-04-05",
  "description" : "A BRAND NEW Macbook Neo",
  "price" : 1500.30
}

### Delete Receipt on ID

DELETE {{url}}/receipt/1