### Get All Users
GET {{url}}/user/all
Accept: application/json
Authorization: Bearer {{token}}

### Get User with ID
GET {{url}}/user/1
Accept: application/json
Authorization: Bearer {{token}}

### Register secure User
POST {{url}}/security/register
Content-Type: application/json

{
  "email": "somethingNewTest@gmail.com",
  "password": "12345678"
}

### Login - Token
POST {{url}}/security/login
Content-Type: application/json

{
  "email": "somethingNewTest@gmail.com",
  "password": "12345678"
}

### Get all products with authorization
GET {{url}}/product/all
Accept: application/json
Authorization: Bearer {{token}}

### Update User on ID
PUT {{url}}/user/3
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "email" : "newEmailAgain@gmail.com",
  "password" : "12345678",
  "createdAt" : "2026-03-08T13:20:00"
}

### Delete User on ID
DELETE {{url}}/user/1
Authorization: Bearer {{token}}