### Get All Warranties

GET {{url}}/warranty/all
Accept: application/json

### Get Warranty with ID

GET {{url}}/warranty/1
Accept: application/json

### Create new Warranty

POST {{url}}/warranty/
Content-Type: application/json

{
    "productId" : 1,
    "warrantyMonths" : 60,
    "startDate" : "2026-03-09"
}

### Update Warranty on ID

PUT {{url}}/warranty/3
Content-Type: application/json

{
  "productId" : 2,
  "warrantyMonths" : 34,
  "startDate" : "2026-04-10"
}

### Delete Warranty on ID

DELETE {{url}}/warranty/1