@baseUrl = http://localhost:7070/warranty

### Get All Warranties

GET {{baseUrl}}/all

### Get Warranty with ID

GET {{baseUrl}}/1

### Create new Warranty

POST {{baseUrl}}/
Content-Type: application/json

{
    "productId" : 1,
    "warrantyMonths" : 60,
    "startDate" : "2026-03-09"
}

### Update Warranty on ID

PUT {{baseUrl}}/3
Content-Type: application/json

{
  "productId" : 2,
  "warrantyMonths" : 34,
  "startDate" : "2026-04-10"
}

### Delete Warranty on ID

DELETE {{baseUrl}}/1